### ISSUE TITLE
Customizing colors

### ISSUE THREAD

**Issue by zakissimo** [utilyre/barbecue.nvim#1]
Hi !

Let me first thank you for saving me the trouble of setting this up myself !

I have a transparent background and somehow it doesn't get removed behind the filename, even with `hl WinBar guibg=NONE`.
Also, I'd like to be able to change the colors dynamically. Do you think I can do that easily ?

Thanks again

**Comment by utilyre** [comment]
Hello dear.

You should be able to make the background transparent by `hl BufferCurrent guibg=NONE` as well as `hl BufferCurrentMod guibg=NONE`. The reason for this is because I made it so winbar will also show whether current buffer is modified or not.

This is just a work around though. I'm planning on adding plugin specific highlights and also an option to opt-out of seeing if buffer is modified.
