### ISSUE TITLE
Using with lualine.nvim

### ISSUE THREAD

**Issue by chinnkarahoi** [utilyre/barbecue.nvim#18]
I found it could be used as a component of lualine.nvim with a little effort of coding to expose a api by which we can  get the winbar data.

**Comment by utilyre** [comment]
An API called `get_entries` is now exposed. See [API](https://github.com/utilyre/barbecue.nvim/tree/main#api).

**Comment by utilyre** [comment]
Also feel free to take inspiration from [build_winbar](https://github.com/utilyre/barbecue.nvim/blob/894bd7a132832bba4d09155567f9e8114d9cc8d4/lua/barbecue/ui.lua#L77-L94) and [Entry:to_string](https://github.com/utilyre/barbecue.nvim/blob/894bd7a132832bba4d09155567f9e8114d9cc8d4/lua/barbecue/ui/entry.lua#L38-L57).

**NOTE**: The `Entry:to_string` is _NOT_ included in each entry you get from the `get_entries` API. This is because `entries` had to be serialized to be save in window variables, thus they could not keep their metatables anymore.

**Comment by EuCaue** [comment]
> An API called `get_entries` is now exposed. See [API](https://github.com/utilyre/barbecue.nvim/tree/894bd7a132832bba4d09155567f9e8114d9cc8d4#api).

I was trying to add to my lualine, but I can't figure out how, you can give an example? 
and it's possible to make always visible, because it's hidden when the cursor stop moving.

**Comment by kaykhan** [comment]
Also trying to get it workign with lualine, does anyone have an example?
