### ISSUE TITLE
[question] Focusing window issue (?)

### ISSUE THREAD

**Issue by brenol** [utilyre/barbecue.nvim#29]
Hi! Great plugin :)

Not sure if a bug, but when doing `:vsplits` and changing between windows with `:wincmd` (or mouse clicking) it resizes the bottom bar up to 50% of the screen, not sure if a bug or a configuration issue. Happens everytime `require('barbecue.ui').toggle()` or `.update()` is called. Any ideas what might be the cause? Looking through ui.lua didn't help me much to identify what is the root cause though.

Here's how it looks after switching from focused window:

![image](https://user-images.githubusercontent.com/7342697/206064486-9f267ad8-4448-42e8-ac8a-e8826dd6719d.png)

(Disabling barbecue fixes  the problem, which makes me think it is causing that behavior, may be a conflict with another plugin though)

Thanks!

**Comment by utilyre** [comment]
All this plugin does is gathering information from nvim-navic and various APIs, arranging them in specific format, and changing the winbar based on the previous step. Thus I don't quite think barbecue is the cause of this issue. If you have neovim nightly installed I'm pretty sure this is a neovim bug which happens when the winbar changes.

**Comment by brenol** [comment]
Thought so. Thanks for the quick answer.

I changed from Neovim 0.8 beta to 0.8.1 yesterday and still have the same issue. I'll play a little with the code to see if I can find out what is causing that behavior on my Neovim and if I find out I'll comment here. Closing for now, thanks!

**Comment by mawkler** [comment]
I have basically the same issue on Neovim 0.8.1, except it resizes one row upward each time I jump to a buffer with barbecue.nvim in it. When I jump to a buffer that doesn't have barbecue.nvim in it the resize doesn't occur, however. I don't have time to create a minimal config right now but [here's](https://github.com/mawkler/nvim) my full config if that's of any help.

**Comment by utilyre** [comment]
As mentioned, this plugin has nothing to do with that bug. Probably try disabling barbecue and just having the winbar set to something like `:set winbar=test` and if it still happens. In that case open an issue on [neovim](https://github.com/neovim/neovim).

**Comment by mawkler** [comment]
The issue seems to lie in [lens.vim](https://github.com/camspiers/lens.vim) combined with winbar. Here's a minimal config to reproduce the issue:

```lua
use { 'utilyre/barbecue.nvim',
  requires = {
    'neovim/nvim-lspconfig',
    'SmiteshP/nvim-navic',
    'nvim-tree/nvim-web-devicons',
  },
  after = 'nvim-web-devicons',
  config = function() require('barbecue').setup({}) end
}
use { 'camspiers/lens.vim' }
```

Setting `winbar` to `test` also doesn't work, so the issue doesn't lie in barbecue as @utilyre said:

```lua
use { 'camspiers/lens.vim',
  config = function()
    vim.o.winbar = 'test'
  end
}
```

Are you by any chance also using lens.vim @brenol?
