### ISSUE TITLE
It seems that barbecus.nvim cannot work with multiple tabpages.

### ISSUE THREAD

**Issue by nyngwang** [utilyre/barbecue.nvim#35]
As title. I used the same default `setup` as README.md, and only those buffers shown in the first tabpage got updated. Buffers that were in the other tabpages just got frozen like: `lua > file.lua`. I also tried `create_autocmd = false` and created it myself, and got the same result.

**Comment by nyngwang** [comment]
I just found a way to make it work:

```lua
require('barbecue').setup {
  attach_navic = false, -- attach navic to LSPs by yourself.
  create_autocmd = false, -- not related, but I also do this myself.
}
```

and then you will need to call this yourself:

```lua
-- In my case, I will call this function in `on_attach`
local function commons(client, bufnr)
  require('nvim-navic').attach(client, bufnr)
  -- and more callbacks.
end
```

**Comment by nyngwang** [comment]
So basically, the following lines don't work:

https://github.com/utilyre/barbecue.nvim/blob/2f242375df96e8a82089d4424e5db0d237c5ae46/lua/barbecue.lua#L16-L24

**Comment by utilyre** [comment]
With a little bit of testing, I found out `require("nvim-navic").is_available` is returning false on both tabs (if I run `:LspRestart` twice on a tab, it'll return true only on that specific tab though).

Thus, I suppose it might be a bug with the `LspAttach` event or buffer-scoped variables (aka `vim.b`). Take a look at these lines from nvim-navic:

https://github.com/SmiteshP/nvim-navic/blob/7a2b823152fe4de65ee7925b0e32d26ed73bc57c/lua/nvim-navic/init.lua#L532-L546

These are the only references of vim.b.navic_client_id (which is why `is_available` returns false). nvim-navic doesn't seem to be setting it to nil anywhere in the code base.

---

Nonetheless, I'll consider documenting this bug in the readme or the wiki.

**Comment by nyngwang** [comment]
@utilyre Thanks for your investigation :) Since it's currently working with the method above, so no problem anymore. Very good plugin, I'm using it and will recommend it to others who haven't tried it.

**Comment by nyngwang** [comment]
I just saw your updates on README.md, many thanks for the work! I believe that will help many people working with multi-tabs. Happy to see that NeoVim is growing to a mature IDE(my dream!) with many great plugin authors!

**Comment by nyngwang** [comment]
@utilyre: Hi, sorry for tagging you on a closed issue, but the code I provided above causes an error(while this is not a big deal, see ref below), which might be good to update the README.md:

> ([Link to above](https://github.com/utilyre/barbecue.nvim/issues/35#issuecomment-1360184840))
> [...]
> 
> ```lua
> -- In my case, I will call this function in `on_attach`.
> local function commons(client, bufnr)
>   -- and more callbacks above.
>   require('nvim-navic').attach(client, bufnr)
>   -- and more callbacks below.
> end
> ```

should be corrected to this instead:

```lua
-- This function will be called by the `on_attach` callback:
local function commons(client, bufnr)
  -- and more callbacks above.
  if client.server_capabilities.documentSymbolProvider then
    require('nvim-navic').attach(client, bufnr)
  end
  -- and more callbacks below.
end
```

Ref: https://github.com/SmiteshP/nvim-navic/issues/7#issuecomment-1154064606

**Comment by utilyre** [comment]
Gotcha!
